// <auto-generated />
namespace NightInn.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ManytoManyThemerelationship2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManytoManyThemerelationship2));
        
        string IMigrationMetadata.Id
        {
            get { return "202101210034484_Many to Many Theme relationship2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
