// <auto-generated />
namespace NightInn.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class firstmigrationsbeforedeployement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstmigrationsbeforedeployement));
        
        string IMigrationMetadata.Id
        {
            get { return "202101291137441_first migrations before deployement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
